In [ ]:
import pandas as pd
dt_test = pd.read_csv('/data/ephemeral/home/train.csv')
dt_test['계약년월'].value_counts().sort_index()
dt_test['계약년월'] = dt_test['계약년월'].astype(str)
dt_test_vali = dt_test[dt_test['계약년월'].isin(['202304', '202305', '202306']) ]
dt_test_train = dt_test[~dt_test['계약년월'].isin(['202304', '202305', '202306']) ]
print(dt_test_train['계약년월'].value_counts().sort_index())
# len(dt_test['계약년월']==2023)

/tmp/ipykernel_501264/2712697157.py:2: DtypeWarning: Columns (16,17,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_test = pd.read_csv('/data/ephemeral/home/train.csv')

200701    4350
200702    3749
200703    5449
200704    4442
200705    3607
          ...
202211     646
202212     855
202301    1488
202302    2539
202303    2889
Name: 계약년월, Length: 195, dtype: int64

In [35]:
import pandas as pd
dt_test = pd.read_csv('/data/ephemeral/home/train.csv')
dt_test.shape

/tmp/ipykernel_501264/2772700258.py:2: DtypeWarning: Columns (16,17,36) have mixed types. Specify dtype option on import or set low_memory=False.
  dt_test = pd.read_csv('/data/ephemeral/home/train.csv')

(1118822, 52)

In [ ]:
import pandas as pd
dt_test = pd.read_csv('/data/ephemeral/home/train.csv')
nullcnt = dt_test.isnull().sum()
notnullcnt = dt_test.notnull().sum()
full_number = pd.concat([nullcnt + notnullcnt], axis=0)
result_dt = pd.DataFrame({
    'null_count': nullcnt,
    'notnull_count': notnullcnt,
    'full_number' : full_number })
display(result_dt)

                        null_count  notnull_count  full_number
시군구                              0           9272         9272
번지                               2           9270         9272
본번                               0           9272         9272
부번                               0           9272         9272
아파트명                            10           9262         9272
전용면적(㎡)                          0           9272         9272
계약년월                             0           9272         9272
계약일                              0           9272         9272
층                                0           9272         9272
건축년도                             0           9272         9272
도로명                              0           9272         9272
해제사유발생일                       9060            212         9272
등기신청일자                           0           9272         9272
거래유형                             0           9272         9272
중개사소재지                           0           9272         9272
k-단지분류(아파트,주상복합등등)            6582           2690         9272
k-전화번호                        6576           2696         9272
k-팩스번호                        6606           2666         9272
단지소개기존clob                    8718            554         9272
k-세대타입(분양형태)                  6562           2710         9272
k-관리방식                        6562           2710         9272
k-복도유형                        6564           2708         9272
k-난방방식                        6562           2710         9272
k-전체동수                        6577           2695         9272
k-전체세대수                       6562           2710         9272
k-건설사(시공사)                    6579           2693         9272
k-시행사                         6580           2692         9272
k-사용검사일-사용승인일                 6563           2709         9272
k-연면적                         6562           2710         9272
k-주거전용면적                      6562           2710         9272
k-관리비부과면적                     6562           2710         9272
k-전용면적별세대현황(60㎡이하)            6562           2710         9272
k-전용면적별세대현황(60㎡~85㎡이하)        6562           2710         9272
k-85㎡~135㎡이하                  6562           2710         9272
k-135㎡초과                      9270              2         9272
k-홈페이지                        7876           1396         9272
k-등록일자                        8554            718         9272
k-수정일자                        6562           2710         9272
고용보험관리번호                      7453           1819         9272
경비비관리형태                       6573           2699         9272
세대전기계약방법                      6642           2630         9272
청소비관리형태                       6573           2699         9272
건축면적                          6565           2707         9272
주차대수                          6563           2709         9272
기타/의무/임대/임의=1/2/3/4           6562           2710         9272
단지승인일                         6568           2704         9272
사용허가여부                        6562           2710         9272
관리비 업로드                       6562           2710         9272
좌표X                           6562           2710         9272
좌표Y                           6562           2710         9272
단지신청일                         6562           2710         9272

In [ ]:
import pandas as pd
dt_train = pd.read_csv('/data/ephemeral/home/train.csv')
# nullcnt = dt_train.isnull().sum()
# notnullcnt = dt_train.notnull().sum()
# full_number = pd.concat([nullcnt + notnullcnt], axis=0)
# result_dt = pd.DataFrame({
#     'null_count': nullcnt,
#     'notnull_count': notnullcnt,
#     'full_number' : full_number })
# # display(result_dt)
display(dt_train['도로명'].value_counts())
display(dt_train['아파트명'].value_counts())
print(len(dt_train['도로명'].unique()))
print(len(dt_train['아파트명'].unique()))
print(len(dt_train['번지'].unique()))

/tmp/ipykernel_501264/4208198181.py:2: DtypeWarning: Columns (16,17,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('/data/ephemeral/home/train.csv')

올림픽로 435         4322
솔샘로 174          3997
송파대로 345         3603
성북로4길 52         3487
양재대로 1340        3369
                 ...
구로동로8길 59           1
구로동로20길 37-13       1
도림로6길 38            1
구로동로18길 44-39       1
시흥대로 224            1
Name: 도로명, Length: 9232, dtype: int64

현대              16644
신동아             12846
한신               9074
두산               8533
주공2              7918
                ...
송파레이크파크호반써밋Ⅱ        1
도곡하이빌               1
창동역블루핀1동            1
한강리버힐B동             1
신용산빌딩               1
Name: 아파트명, Length: 6538, dtype: int64

9232
6539
6573

In [11]:
import pandas as pd
df_train = pd.read_csv('/data/ephemeral/home/train.csv')
display([df_train['도로명'] == ' '])

/tmp/ipykernel_501264/3434483529.py:2: DtypeWarning: Columns (16,17,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('/data/ephemeral/home/train.csv')

[0          False
 1          False
 2          False
 3          False
 4          False
            ...
 1118817    False
 1118818    False
 1118819    False
 1118820    False
 1118821    False
 Name: 도로명, Length: 1118822, dtype: bool]

In [1]:
df_train['full_address'] = df_train['시군구'] + df_train['도로명']
print(df_train['full_address'])

NameError: name 'df_train' is not defined

In [34]:
# display(df[df['번지'].isnull()])
df_train['full_address'] = dt_train['시군구'] + df_train['도로명']
df_address_needed = df_train[df_train['좌표X'].isnull()][['도로명']]
df_address_needed_index = dt_address_needed.index
display(df_address_needed)
display(dt_address_needed_index)

NameError: name 'dt_train' is not defined

In [ ]:
# 앞서 예측한 예측값들을 저장합니다.
# fill_needed = pd.DataFrame(dt_address_needed)
# fill_needed.to_csv('null-x.csv')

In [29]:
%pip install geopy
#데이터의 좌표주소 열을 이용해 지오코딩
for i, loc in enumerate(fill_needed['도로명']):
    coord = geolocator.geocode(loc)[-1]
    fill_needed.loc[i, '위도'] = coord[0]
    fill_needed.loc[i, '경도'] = coord[1]
print(fill_needed)

Requirement already satisfied: geopy in /opt/conda/lib/python3.10/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/conda/lib/python3.10/site-packages (from geopy) (2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

NameError: name 'geolocator' is not defined