In [2]:
import pandas as pd
df_train = pd.read_csv('C:\\Daun\\train.csv')
nullcnt = df_train.isnull().sum()
notnullcnt = df_train.notnull().sum()
full_number = pd.concat([nullcnt + notnullcnt], axis=0)
result_df = pd.DataFrame({
    'null_count': nullcnt,
    'notnull_count': notnullcnt,
    'full_number' : full_number })
display(result_df)

C:\Users\aidan\AppData\Local\Temp\ipykernel_27020\2706409819.py:2: DtypeWarning: Columns (16,17,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('C:\\Daun\\train.csv')

                        null_count  notnull_count  full_number
시군구                              0        1118822      1118822
번지                             225        1118597      1118822
본번                              75        1118747      1118822
부번                              75        1118747      1118822
아파트명                          2126        1116696      1118822
전용면적(㎡)                          0        1118822      1118822
계약년월                             0        1118822      1118822
계약일                              0        1118822      1118822
층                                0        1118822      1118822
건축년도                             0        1118822      1118822
도로명                              0        1118822      1118822
해제사유발생일                    1112839           5983      1118822
등기신청일자                           0        1118822      1118822
거래유형                             0        1118822      1118822
중개사소재지                           0        1118822      1118822
k-단지분류(아파트,주상복합등등)          870691         248131      1118822
k-전화번호                      870274         248548      1118822
k-팩스번호                      872742         246080      1118822
단지소개기존clob                 1050240          68582      1118822
k-세대타입(분양형태)                869563         249259      1118822
k-관리방식                      869563         249259      1118822
k-복도유형                      869890         248932      1118822
k-난방방식                      869563         249259      1118822
k-전체동수                      870630         248192      1118822
k-전체세대수                     869563         249259      1118822
k-건설사(시공사)                  871058         247764      1118822
k-시행사                       871254         247568      1118822
k-사용검사일-사용승인일               869696         249126      1118822
k-연면적                       869563         249259      1118822
k-주거전용면적                    869608         249214      1118822
k-관리비부과면적                   869563         249259      1118822
k-전용면적별세대현황(60㎡이하)          869608         249214      1118822
k-전용면적별세대현황(60㎡~85㎡이하)      869608         249214      1118822
k-85㎡~135㎡이하                869608         249214      1118822
k-135㎡초과                   1118495            327      1118822
k-홈페이지                     1005647         113175      1118822
k-등록일자                     1107832          10990      1118822
k-수정일자                      869608         249214      1118822
고용보험관리번호                    913304         205518      1118822
경비비관리형태                     870988         247834      1118822
세대전기계약방법                    878747         240075      1118822
청소비관리형태                     871178         247644      1118822
건축면적                        869714         249108      1118822
주차대수                        869714         249108      1118822
기타/의무/임대/임의=1/2/3/4         869563         249259      1118822
단지승인일                       870286         248536      1118822
사용허가여부                      869563         249259      1118822
관리비 업로드                     869563         249259      1118822
좌표X                         869670         249152      1118822
좌표Y                         869670         249152      1118822
단지신청일                       869625         249197      1118822
target                           0        1118822      1118822

In [11]:
# df_train['도로명'].value_counts()
df_add = df_train[df_train['도로명'].apply(len) < 3]
display(df_add, len(df_add))

,시군구,번지,본번,부번,아파트명,전용면적(㎡),계약년월,계약일,층,건축년도,...,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일,target
63981,서울특별시 성동구 하왕십리동,1071,1071.0,0.0,왕십리자이,59.99,201807,15,2,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74000
63986,서울특별시 성동구 하왕십리동,1071,1071.0,0.0,왕십리자이,84.99,201809,19,1,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101381
63987,서울특별시 성동구 하왕십리동,1071,1071.0,0.0,왕십리자이,84.99,201809,20,14,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93909
82306,서울특별시 영등포구 당산동4가,99,99.0,0.0,당산롯데캐슬프레스티지,84.98,201808,16,13,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110000
82307,서울특별시 영등포구 당산동4가,99,99.0,0.0,당산롯데캐슬프레스티지,84.98,201808,20,19,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115471,서울특별시 종로구 옥인동,179-3,179.0,3.0,옥인시민,59.50,200709,8,2,1971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26500
1115472,서울특별시 종로구 옥인동,179-3,179.0,3.0,옥인시민,59.50,200709,19,4,1971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28400
1115595,서울특별시 종로구 평창동,596,596.0,0.0,삼성,84.98,200701,10,5,1998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27500
1115601,서울특별시 종로구 평창동,596,596.0,0.0,삼성,84.93,200706,27,6,1998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30700
1115602,서울특별시 종로구 평창동,596,596.0,0.0,삼성,84.93,200707,6,5,1998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25000

1209

In [3]:
# display(df[df['번지'].isnull()])
df_address_needed = df_train[df_train['좌표X'].isnull()][['도로명']]
df_address_needed_index = df_address_needed.index
display(df_address_needed)
display(df_address_needed_index)

                 도로명
975           삼성로 14
976           삼성로 14
977           삼성로 14
978           삼성로 14
979           삼성로 14
...              ...
1118203   동일로144길 74
1118204  봉화산로27가길 23
1118205  봉화산로27가길 23
1118206  봉화산로27가길 23
1118207  봉화산로27가길 19

[869670 rows x 1 columns]

Index([    975,     976,     977,     978,     979,     980,     981,     982,
           983,     984,
       ...
       1118198, 1118199, 1118200, 1118201, 1118202, 1118203, 1118204, 1118205,
       1118206, 1118207],
      dtype='int64', length=869670)

In [ ]:
# 앞서 예측한 예측값들을 저장합니다.
df_address_needed.to_csv('null2-x.csv')

In [4]:
%pip install geopy
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="myGeocoder")

# 위도와 경도 열을 미리 생성
df_address_needed['위도'] = None
df_address_needed['경도'] = None

#데이터의 좌표주소 열을 이용해 지오코딩
for i, loc in enumerate(df_address_needed['도로명']):
    coord = geolocator.geocode(loc)[-1]
    df_address_needed.loc[i, '위도'] = coord[0]
    df_address_needed.loc[i, '경도'] = coord[1]
print(df_address_needed)

Requirement already satisfied: geopy in c:\users\aidan\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\aidan\anaconda3\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

GeocoderInsufficientPrivileges: Non-successful status code 403